### load extenstions ###

source "$HOME/.git-completion.bash"
source "$HOME/.git-prompt.sh"

### ENV variables ###

# look for commands in these places
export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$HOME/.bin:$PATH"

# make vim the default text editor
export EDITOR="vim"

# shortened prompt that includes git branch info
YELLOW='\[\e[0;33m\]'
WHITE='\[\e[1;37m\]'
RESET='\[\e[0m\]'
export PS1="$YELLOW\W$WHITE\$(__git_ps1)$YELLOW\$$RESET "
### other ###

# initialize rbenv
eval "$(rbenv init -)"

# initialize node version manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

# load aliases
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# load any local configuration
[[ -f "$HOME/.bashrc.local" ]] && source "$HOME/.bashrc.local"

# bash colors
export CLICOLOR=1
export LSCOLORS=gxfxcxdxbxegedabagacad

#mv grabs dotfiles
shopt -s dotglob

# added by Anaconda3 5.2.0 installer
export PATH="/anaconda3/bin:$PATH"

# app academy shit
alias gradingtime="source ~/appacademy/assess_grader.sh"

# shell integration
# allows 'jump to previous input', which is actually 'Previous Mark'
source ~/.iterm2_shell_integration.bash